name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - run: python -m pip install .[build]
    - run: python -m pip install .[test]
    - run: python setup.py sdist bdist_wheel
    - run: twine check dist/*
    - run: pytest
